---
on:
  push:
    branches:
      - main
name: deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: michaelpeterswa/rust-wasm-pack-action@v1.0.0
        env:
          WASM_PACK_TARGET: web
          WASM_PACK_IN_DIR: .
          WASM_PACK_OUT_DIR: frontend/build

      - uses: actions/setup-node@v3
      - run: sudo npm ci --save-dev
        working-directory: frontend
      - run: npm run build
        working-directory: frontend

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./frontend/build
