---
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

name: deploy
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: michaelpeterswa/rust-wasm-pack-action@v1.0.0
        env:
          WASM_PACK_TARGET: web
          WASM_PACK_IN_DIR: .
          WASM_PACK_OUT_DIR: frontend/build

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: |
          npm ci
          npm run build
        working-directory: frontend
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'frontend/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
